name: run npm-version pipeline
on: push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
        
      - name: 'change version'
        uses: polygon-software/npm-version-date@master
        with:
          schema: 'V.yyMd.hm'
          V: '1'
          increase-patch: true
      

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}